import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/sub-components/Navbar";
import TopLoader from "@/components/sub-components/TopLoader";
import Footer from "@/components/sub-components/Footer";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  adjustFontFallback: false,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopLoader />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
