import "./../globals.css";
import Navbar from "@/components/sub-components/Navbar";
import TopLoader from "@/components/sub-components/TopLoader";
import Footer from "@/components/sub-components/Footer";
import { Inter } from "next/font/google";
import SideNavbar from "@/components/sub-components/SideNavbar";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>
      <SideNavbar />
      <div className="admin-contents">{children}</div>
    </>
  );
}
